base_url = "https://peperoncino000.netlify.com"
compile_sass = true
highlight_code = true
build_search_index = true
theme = "terminimal"
title = "peperoncino000's tech blog"
taxonomies = [
    {name = "categories"},
    {name = "tags", paginate_by = 5, rss = true},
]


[extra]
logo_text = "peperoncino000's tech blog"
accent_color = "green"
background_color = "dark"
author = "Keisuke Toyota"
copyright_html = "2019 Keisuke Toyota"
use_full_hack_font = true
post_view_navigation_prompt = "Read more"
ga_id = "UA-111474214-2"
menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "about me", url = "$BASE_URL/about"},
    
    {name = "github", url = "https://github.com/KeisukeToyota", newtab = true},
    {name = "twitter", url = "https://twitter.com/peperoncino000", newtab = true},
    {name = "lapras", url = "https://lapras.com/public/BE7TXA7", newtab = true},
]