base_url = "https://ksk.works"
compile_sass = true
build_search_index = true
theme = "terminimal"
title = "ksk's tech blog"
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
taxonomies = [
  { name = "categories" },
  { name = "tags", paginate_by = 5, rss = true },
]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
logo_text = "ksk's tech blog"
accent_color = "green"
background_color = "dark"
author = "Keisuke Toyota"
copyright_html = "2019 Keisuke Toyota"
use_full_hack_font = true
post_view_navigation_prompt = "Thanks for reading!"
ga_id = "UA-111474214-2"
favicon = "favicon/favicon.ico"
meta_description = "ksk's tech blog."
menu_items = [
  { name = "Blog", url = "$BASE_URL" },
  { name = "Tags", url = "$BASE_URL/tags" },
  { name = "About me", url = "$BASE_URL/about" },
  { name = "GitHub", url = "https://github.com/ksk001100", newtab = true },
  { name = "X (formerly Twitter)", url = "https://twitter.com/ksk001100", newtab = true },
  { name = "Bluesky", url = "https://bsky.app/profile/ksk.works", newtab = true },
  { name = "Lapras", url = "https://lapras.com/public/ksk", newtab = true },
]

[search]
include_title = true
include_description = false
include_path = false
include_content = true
